# Tomcat 配置
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 7788



zk:
    servers: 111.230.210.81:2181
    rootPath: /cloud
    listener:
            - lisi
            - zhaoliu





